//
//  main.cpp
//  PE_93 (arithmetic expressions)
//
//  Created by Neil Marshall on 02/05/2016.
//  Copyright © 2016 Neil Marshall. All rights reserved.
//

#include <iostream>
#include "token.hpp"

using namespace std;

int main() {

    int SequentialIntegers = 0;
    int MaxSequentialIntegers = 0;
    int result_a = 0;
    int result_b = 0;
    int result_c = 0;
    int result_d = 0;

    for (int a = 1; a <= 6; ++a) {
        for (int b = a+1; b <= 7; ++b) {
            for (int c = b+1; c <= 8; ++c) {
                for (int d = c+1; d <= 9; ++d) {
                    if (a != b && a != c && a != d && b != c && b != d && c != d) {
                        cout << "a = " << a << ", b = " << b << ", c = " << c << ", d = " << d << endl;
                        SequentialIntegers = fnSequentialIntegers(a, b, c, d);
                        if (SequentialIntegers > MaxSequentialIntegers) {
                            MaxSequentialIntegers = SequentialIntegers;
                            result_a = a;
                            result_b = b;
                            result_c = c;
                            result_d = d;
                            fnPrintResults(a, b, c, d);
                        }
                        cout << "Current maximal sequence length: " << MaxSequentialIntegers << "(" << result_a << result_b << result_c << result_d << ")" << endl;
                    }
                }
            }
        }
    }
    
    cout << "Maximum number of sequential integers is: " << MaxSequentialIntegers << endl;
    cout << "Result generated by: " << result_a << ", " << result_b << ", " << result_c << ", " << result_d << endl;
    return 0;
}
